In [1]:
from hdmf_zarr import NWBZarrIO

In [2]:
with NWBZarrIO("/root/capsule/results/behavior.nwb.zarr", "r") as io:
    nwb = io.read()

In [13]:
nwb.processing["Behavior"]["Sniffing"]

Sniffing pynwb.base.TimeSeries at 0x139869079065408
Fields:
  comments: no comments
  conversion: 1.0
  data: <zarr.core.Array '/processing/Behavior/Sniffing/data' (708484,) uint16 read-only>
  description: no description
  interval: 1
  offset: 0.0
  resolution: -1.0
  timestamps: <zarr.core.Array '/processing/Behavior/Sniffing/timestamps' (708484,) float64 read-only>
  timestamps_unit: seconds
  unit: V

In [5]:
events = nwb.get_events__events_tables()
events_df = events.to_dataframe()
meanings = events.meanings_tables["meanings"][:]

In [7]:
events_df

,timestamp,event_type,site_index,patch_index,block_index,reward_volume,concentration_ch0,concentration_ch1,concentration_ch2
id,,,,,,,,,
0,4.149219e+06,stop_onset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,4.149219e+06,stop_offset,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,4.149219e+06,block_onset,NaN,NaN,0.0,NaN,NaN,NaN,NaN
3,4.149219e+06,patch_enter,NaN,0.0,NaN,NaN,NaN,NaN,NaN
4,4.149220e+06,inter_patch_enter,0.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
3754,4.152044e+06,tone,858.0,NaN,NaN,NaN,NaN,NaN,NaN
3755,4.152047e+06,reward_site_exit,858.0,NaN,NaN,NaN,NaN,NaN,NaN
3756,4.152047e+06,inter_site_enter,859.0,NaN,NaN,NaN,NaN,NaN,NaN
3757,4.152047e+06,odor_offset,858.0,NaN,NaN,NaN,1.0,0.0,0.0
3758,4.152048e+06,inter_site_exit,859.0,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
meanings

,value,meaning,hed_tag
id,,,
0,reward_site_enter,The time when the mouse enters a virtual locat...,"Agent-action, ((Animal-agent, Experiment-parti..."
1,reward_site_exit,The time when the mouse exits a virtual locati...,"Agent-action, ((Animal-agent, Experiment-parti..."
2,odor_onset,The onset of the odor that is presented for ev...,"(Def/Odor, (Sensory-event, Olfactory-presentat..."
3,odor_offset,The offset of the odor that is presented for e...,"(Def/Odor, Offset)"
4,reward,Water reward that motivates mice to run down t...,"Sensory-event, Gustatory-presentation, (Ingest..."
5,lick,Time when mouse licks the lick spout.,"Agent-action, (Animal-agent, Lick)"
6,tone,Auditory cue that indicates to the mouse that ...,"Sensory-event, Cue, (Auditory-presentation, (T..."
7,patch_enter,Time when the mouse enters the virtual locatio...,"Agent-action, ((Animal-agent, Experiment-parti..."
8,patch_exit,Time when the mouse exits the virtual location...,"Agent-action, ((Animal-agent, Experiment-parti..."
9,block_onset,Time block when experimental statistics in the...,"(Def/Block, (Experiment-structure, Label/block..."
10,block_offset,The offset of the time block when experimental...,"(Def/Block, Offset)"
11,inter_site_enter,Time when the mouse enters the virtual locatio...,"Agent-action, ((Animal-agent, Experiment-parti..."
12,inter_site_exit,Time when the mouse exits the virtual location...,"Agent-action, ((Animal-agent, Experiment-parti..."
13,inter_patch_enter,Time when the mouse enters the virtual locatio...,"Agent-action, ((Animal-agent, Experiment-parti..."
14,inter_patch_exit,Time when the mouse exits the virtual location...,"Agent-action, ((Animal-agent, Experiment-parti..."
15,reward_probability,The probability of reward when the reward curv...,"Measurement-event, Probability/#, Description/..."
16,stop_onset,When the velocity of the mouse slows to the st...,"Agent-action, (Animal-agent, Experiment-partic..."
17,stop_offset,When the velocity of the mouse exceeds the sto...,"Agent-action, (Animal-agent, Experiment-partic..."